TARGET          = balanser
BOARD_TAG       = uno

OBJDIR          = build

LOCAL_CPP_SRCS += ${wildcard src/*.cpp}

CXXFLAGS        = -std=c++14

F_CPU           = 16000000

ARDUINO_DIR     = /usr/share/arduino
USER_LIB_PATH   = ../lib

include $(ARDUINO_DIR)/Arduino.mk

